"""
importer.py
-----------
Orchestrates the full import pipeline:
  load CSV → group splits → dedup → format → return journal text

This module has no CLI concerns — those live in __main__.py.
"""

import csv
import re
import sys
from datetime import datetime
from pathlib import Path

from . import config as cfg_mod
from . import fingerprint as fp_mod
from . import formatter
from . import splitter


def load_csv(filepath: str | Path) -> list[dict]:
    with open(filepath, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _should_skip(row: dict, config: dict) -> bool:
    if row["Payee"] in set(config["skip_payees"]):
        return True
    if re.search(r"starting balance", row["Notes"], re.IGNORECASE):
        return True
    # Rows with no category, zero amount, and not a split parent are noise
    # (e.g. clearing account pass-through legs that slipped through)
    if (
        not row["Category"]
        and float(row["Amount"] or 0) == 0
        and not splitter.is_split_parent(row["Notes"])
    ):
        return True
    return False


def run(
    filepath: str | Path,
    config: dict,
    currency: str | None    = None,
    no_splits: bool         = False,
    warn_unmatched: bool    = False,
    seen_ids: set[str]      = None,
) -> tuple[str, dict]:
    """
    Import an Actual Budget CSV export and return (journal_text, stats).

    Parameters
    ----------
    filepath       : Path to the Actual Budget CSV export file.
    config         : Loaded config dict (from config.load()).
    currency       : Override currency symbol (default: from config).
    no_splits      : If True, import split rows as individual simple transactions.
    warn_unmatched : If True, print stderr warnings for orphaned split parents.
    seen_ids       : Set of fingerprints already in the journal — these are skipped.

    Returns
    -------
    (journal_text, stats) where stats has keys:
        written, skipped, dupes, orphans
    """
    if seen_ids is None:
        seen_ids = set()
    if currency is None:
        currency = cfg_mod.currency(config)

    filepath = Path(filepath)
    rows     = load_csv(filepath)
    groups   = splitter.group(rows)

    header_lines = [
        f"; Generated by actual-budget-import",
        f"; Source:    {filepath.name}",
        f"; Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"; Rows: {len(rows)}  Groups: {len(groups)}  "
        f"Dedup against: {len(seen_ids)} existing fingerprints",
        f";",
        f"; To include in your main journal:",
        f";   include 2026/2026.journal",
        "",
    ]

    output_lines: list[str]          = list(header_lines)
    written = skipped = dupes = orphans = 0

    for item in groups:

        # ── split group ───────────────────────────────────────────────────────
        if isinstance(item, tuple) and item[0] == "split":
            _, parent, children = item
            if _should_skip(parent, config):
                skipped += 1
                continue
            fprint = fp_mod.compute(parent)
            if fprint in seen_ids:
                dupes += 1
                continue

            if no_splits or not children:
                # Degrade to simple transaction using the parent's Split_Amount
                pseudo           = dict(parent)
                pseudo["Amount"] = parent["Split_Amount"]
                pseudo["Notes"]  = re.sub(
                    r"^\(SPLIT INTO \d+\)\s*", "", parent["Notes"]
                ).strip()
                output_lines.append(formatter.simple(pseudo, currency, config))
            else:
                output_lines.append(
                    formatter.split(parent, children, currency, config)
                )
            written += 1

        # ── orphaned split parent ─────────────────────────────────────────────
        elif isinstance(item, tuple) and item[0] == "split-orphan":
            _, parent, partial = item
            if _should_skip(parent, config):
                skipped += 1
                continue
            fprint = fp_mod.compute(parent)
            if fprint in seen_ids:
                dupes += 1
                continue

            if warn_unmatched:
                m = re.match(r"^\(SPLIT INTO (\d+)\)", parent["Notes"])
                expected = m.group(1) if m else "?"
                print(
                    f"WARNING: split orphan [{parent['Date']} {parent['Payee']}] "
                    f"— expected {expected} children, found {len(partial)}.",
                    file=sys.stderr,
                )
            output_lines.append(formatter.orphan(parent, partial, currency, config))
            written  += 1
            orphans  += 1

        # ── simple transaction ────────────────────────────────────────────────
        else:
            row = item
            if _should_skip(row, config):
                skipped += 1
                continue
            fprint = fp_mod.compute(row)
            if fprint in seen_ids:
                dupes += 1
                continue
            output_lines.append(formatter.simple(row, currency, config))
            written += 1

    stats = dict(written=written, skipped=skipped, dupes=dupes, orphans=orphans)
    output_lines.append(
        f"; Import complete: {written} written, {skipped} skipped, "
        f"{dupes} duplicates suppressed"
        + (f", {orphans} orphaned splits" if orphans else "")
    )
    return "\n".join(output_lines), stats
